services:
  - type: web
    name: gemini-alternative-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: reflex run --env prod --backend-only --backend-host 0.0.0.0 --backend-port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gemini-alternative-db
          property: connectionString
  - type: static
    name: gemini-alternative-ui
    buildCommand: reflex export --frontend-only --no-zip --env prod
    staticPublishPath: .web/build/client
    envVars:
      - key: REFLEX_API_URL
        value: https://gemini-alternative-api.onrender.com
databases:
  - name: gemini-alternative-db
    plan: free
